services:
  app:
    build: .
    container_name: uned-group-links-dev
    ports:
      - "3001:3000"
    volumes:
      - .:/app:z
      - /app/node_modules
    environment:
      - CHOKIDAR_USEPOLLING=true
      - WATCHPACK_POLLING=true
      - FAST_REFRESH=true
      - WDS_SOCKET_PORT=3001
    stdin_open: true
    tty: true
    command: npm start
